version: "2"
services:
  nginx:
    build:
      context: nginx
      dockerfile: ./Dockerfile
    volumes:
      - ../:/var/www
    ports:
      - 8012:80
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../:/var/www
    links:
      - mysql
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_database=sample
    ports:
      - 3310:3306
    volumes:
      - ../datadir:/var/lib/mysql

